# https://starship.rs/config/
"$schema" = "https://starship.rs/config-schema.json"

# A minimal left prompt:
# format = """$character"""
# right_format = """$all"""

[battery]
disabled = true

[cmd_duration]
min_time = 2500
style = "bold cyan"

[container]
disabled = true

[directory]
truncation_length = 0
truncate_to_repo = false
read_only = " "

[directory.substitutions]
"~" = "󰌾 ~"
" ~/Documents" = " ~/Documents"
" ~/Downloads" = " ~/Downloads"
" ~/Desktop" = " ~/Desktop"
" ~/Music" = " ~/Music"
" ~/Pictures" = " ~/Pictures"
" ~/Library" = " ~/Library"
" ~/Dropbox" = " ~/Dropbox"
" ~/source" = " ~/source"
" ~/.dotfiles" = " ~/.dotfiles"

[docker_context]
symbol = " "

[gcloud]
disabled = true

[git_branch]
symbol = " "
style = "bold green"

[git_commit]
tag_symbol = '  '
tag_disabled = false
format = "[ $hash$tag]($style) "
style = "bold blue"

[git_status]
style = "bold yellow"
format = "([ $all_status$ahead_behind]($style) )"
ignore_submodules = true
renamed = ""
deleted = ""
stashed = ""

[golang]
symbol = " "

[hostname]
ssh_only = true
ssh_symbol = " "
style = "bold green"
format = "[$ssh_symbol$hostname]($style) "

[localip]
disabled = true

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[nodejs]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[conda]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[username]
format = "[ $user]($style) "
style_root = "bold bright-red"
style_user = "bold bright-red"

[vagrant]
disabled = true